global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'nestjs-microservices'
    metrics_path: '/api/telemetry/metrics'
    static_configs:
      - targets: 
        - 'servicio-identidad:3000'
        - 'servicio-mesas:3000'
        - 'servicio-pedidos:3000'
        - 'servicio-cuentas:3000'
        - 'servicio-reservas:3000'
        - 'servicio-inventario:3000'
        - 'servicio-notificaciones:3000'
        - 'servicio-caja:3000'
        - 'servicio-reportes:3000'
